// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCITQgPa8rY5SuPNZuryXNZV__Ll6_1COY',
    appId: '1:184739830401:web:56cbbd0821ef10e6ca4b80',
    messagingSenderId: '184739830401',
    projectId: 'eduroad-36d01',
    authDomain: 'eduroad-36d01.firebaseapp.com',
    storageBucket: 'eduroad-36d01.firebasestorage.app',
    measurementId: 'G-8ZMNK1B5TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVtuuDq94TMjdDu8SeUbs_zBu6_dYmGmE',
    appId: '1:184739830401:android:4cdaef4894dbebd5ca4b80',
    messagingSenderId: '184739830401',
    projectId: 'eduroad-36d01',
    storageBucket: 'eduroad-36d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO0e5TJ-gVmsgWvWFl7q97WN0DD6B-IBI',
    appId: '1:184739830401:ios:7a1a068fb5fdde90ca4b80',
    messagingSenderId: '184739830401',
    projectId: 'eduroad-36d01',
    storageBucket: 'eduroad-36d01.firebasestorage.app',
    iosBundleId: 'com.example.eduroad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO0e5TJ-gVmsgWvWFl7q97WN0DD6B-IBI',
    appId: '1:184739830401:ios:7a1a068fb5fdde90ca4b80',
    messagingSenderId: '184739830401',
    projectId: 'eduroad-36d01',
    storageBucket: 'eduroad-36d01.firebasestorage.app',
    iosBundleId: 'com.example.eduroad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCITQgPa8rY5SuPNZuryXNZV__Ll6_1COY',
    appId: '1:184739830401:web:14e4e19f1b27b10aca4b80',
    messagingSenderId: '184739830401',
    projectId: 'eduroad-36d01',
    authDomain: 'eduroad-36d01.firebaseapp.com',
    storageBucket: 'eduroad-36d01.firebasestorage.app',
    measurementId: 'G-MXGNZ9E5E0',
  );
}
